/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedFinancialIndexRouteImport } from './routes/_authenticated/financial/index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated/agenda/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings/permissions'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsFinancialRouteImport } from './routes/_authenticated/settings/financial'
import { Route as AuthenticatedSettingsAgendaRouteImport } from './routes/_authenticated/settings/agenda'
import { Route as AuthenticatedFinancialRevenuesRouteImport } from './routes/_authenticated/financial/revenues'
import { Route as AuthenticatedFinancialReportsRouteImport } from './routes/_authenticated/financial/reports'
import { Route as AuthenticatedFinancialQuotasRouteImport } from './routes/_authenticated/financial/quotas'
import { Route as AuthenticatedFinancialPayablesRouteImport } from './routes/_authenticated/financial/payables'
import { Route as AuthenticatedFinancialNewRouteImport } from './routes/_authenticated/financial/new'
import { Route as AuthenticatedFinancialFixedRouteImport } from './routes/_authenticated/financial/fixed'
import { Route as AuthenticatedFinancialExpensesRouteImport } from './routes/_authenticated/financial/expenses'
import { Route as AuthenticatedFinancialIdRouteImport } from './routes/_authenticated/financial/$id'
import { Route as AuthenticatedAgendaProposalsRouteImport } from './routes/_authenticated/agenda/proposals'
import { Route as AuthenticatedAgendaNewRouteImport } from './routes/_authenticated/agenda/new'
import { Route as AuthenticatedAgendaIdRouteImport } from './routes/_authenticated/agenda/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialIndexRoute =
  AuthenticatedFinancialIndexRouteImport.update({
    id: '/financial/',
    path: '/financial/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsFinancialRoute =
  AuthenticatedSettingsFinancialRouteImport.update({
    id: '/settings/financial',
    path: '/settings/financial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAgendaRoute =
  AuthenticatedSettingsAgendaRouteImport.update({
    id: '/settings/agenda',
    path: '/settings/agenda',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialRevenuesRoute =
  AuthenticatedFinancialRevenuesRouteImport.update({
    id: '/financial/revenues',
    path: '/financial/revenues',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialReportsRoute =
  AuthenticatedFinancialReportsRouteImport.update({
    id: '/financial/reports',
    path: '/financial/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialQuotasRoute =
  AuthenticatedFinancialQuotasRouteImport.update({
    id: '/financial/quotas',
    path: '/financial/quotas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialPayablesRoute =
  AuthenticatedFinancialPayablesRouteImport.update({
    id: '/financial/payables',
    path: '/financial/payables',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialNewRoute =
  AuthenticatedFinancialNewRouteImport.update({
    id: '/financial/new',
    path: '/financial/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialFixedRoute =
  AuthenticatedFinancialFixedRouteImport.update({
    id: '/financial/fixed',
    path: '/financial/fixed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialExpensesRoute =
  AuthenticatedFinancialExpensesRouteImport.update({
    id: '/financial/expenses',
    path: '/financial/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialIdRoute =
  AuthenticatedFinancialIdRouteImport.update({
    id: '/financial/$id',
    path: '/financial/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaProposalsRoute =
  AuthenticatedAgendaProposalsRouteImport.update({
    id: '/agenda/proposals',
    path: '/agenda/proposals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaNewRoute = AuthenticatedAgendaNewRouteImport.update({
  id: '/agenda/new',
  path: '/agenda/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaIdRoute = AuthenticatedAgendaIdRouteImport.update({
  id: '/agenda/$id',
  path: '/agenda/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agenda/$id': typeof AuthenticatedAgendaIdRoute
  '/agenda/new': typeof AuthenticatedAgendaNewRoute
  '/agenda/proposals': typeof AuthenticatedAgendaProposalsRoute
  '/financial/$id': typeof AuthenticatedFinancialIdRoute
  '/financial/expenses': typeof AuthenticatedFinancialExpensesRoute
  '/financial/fixed': typeof AuthenticatedFinancialFixedRoute
  '/financial/new': typeof AuthenticatedFinancialNewRoute
  '/financial/payables': typeof AuthenticatedFinancialPayablesRoute
  '/financial/quotas': typeof AuthenticatedFinancialQuotasRoute
  '/financial/reports': typeof AuthenticatedFinancialReportsRoute
  '/financial/revenues': typeof AuthenticatedFinancialRevenuesRoute
  '/settings/agenda': typeof AuthenticatedSettingsAgendaRoute
  '/settings/financial': typeof AuthenticatedSettingsFinancialRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/financial/': typeof AuthenticatedFinancialIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/agenda/$id': typeof AuthenticatedAgendaIdRoute
  '/agenda/new': typeof AuthenticatedAgendaNewRoute
  '/agenda/proposals': typeof AuthenticatedAgendaProposalsRoute
  '/financial/$id': typeof AuthenticatedFinancialIdRoute
  '/financial/expenses': typeof AuthenticatedFinancialExpensesRoute
  '/financial/fixed': typeof AuthenticatedFinancialFixedRoute
  '/financial/new': typeof AuthenticatedFinancialNewRoute
  '/financial/payables': typeof AuthenticatedFinancialPayablesRoute
  '/financial/quotas': typeof AuthenticatedFinancialQuotasRoute
  '/financial/reports': typeof AuthenticatedFinancialReportsRoute
  '/financial/revenues': typeof AuthenticatedFinancialRevenuesRoute
  '/settings/agenda': typeof AuthenticatedSettingsAgendaRoute
  '/settings/financial': typeof AuthenticatedSettingsFinancialRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/financial': typeof AuthenticatedFinancialIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agenda/$id': typeof AuthenticatedAgendaIdRoute
  '/_authenticated/agenda/new': typeof AuthenticatedAgendaNewRoute
  '/_authenticated/agenda/proposals': typeof AuthenticatedAgendaProposalsRoute
  '/_authenticated/financial/$id': typeof AuthenticatedFinancialIdRoute
  '/_authenticated/financial/expenses': typeof AuthenticatedFinancialExpensesRoute
  '/_authenticated/financial/fixed': typeof AuthenticatedFinancialFixedRoute
  '/_authenticated/financial/new': typeof AuthenticatedFinancialNewRoute
  '/_authenticated/financial/payables': typeof AuthenticatedFinancialPayablesRoute
  '/_authenticated/financial/quotas': typeof AuthenticatedFinancialQuotasRoute
  '/_authenticated/financial/reports': typeof AuthenticatedFinancialReportsRoute
  '/_authenticated/financial/revenues': typeof AuthenticatedFinancialRevenuesRoute
  '/_authenticated/settings/agenda': typeof AuthenticatedSettingsAgendaRoute
  '/_authenticated/settings/financial': typeof AuthenticatedSettingsFinancialRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/financial/': typeof AuthenticatedFinancialIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/agenda/$id'
    | '/agenda/new'
    | '/agenda/proposals'
    | '/financial/$id'
    | '/financial/expenses'
    | '/financial/fixed'
    | '/financial/new'
    | '/financial/payables'
    | '/financial/quotas'
    | '/financial/reports'
    | '/financial/revenues'
    | '/settings/agenda'
    | '/settings/financial'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/users'
    | '/agenda/'
    | '/financial/'
    | '/notifications/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/agenda/$id'
    | '/agenda/new'
    | '/agenda/proposals'
    | '/financial/$id'
    | '/financial/expenses'
    | '/financial/fixed'
    | '/financial/new'
    | '/financial/payables'
    | '/financial/quotas'
    | '/financial/reports'
    | '/financial/revenues'
    | '/settings/agenda'
    | '/settings/financial'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/users'
    | '/agenda'
    | '/financial'
    | '/notifications'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/agenda/$id'
    | '/_authenticated/agenda/new'
    | '/_authenticated/agenda/proposals'
    | '/_authenticated/financial/$id'
    | '/_authenticated/financial/expenses'
    | '/_authenticated/financial/fixed'
    | '/_authenticated/financial/new'
    | '/_authenticated/financial/payables'
    | '/_authenticated/financial/quotas'
    | '/_authenticated/financial/reports'
    | '/_authenticated/financial/revenues'
    | '/_authenticated/settings/agenda'
    | '/_authenticated/settings/financial'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/users'
    | '/_authenticated/agenda/'
    | '/_authenticated/financial/'
    | '/_authenticated/notifications/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/': {
      id: '/_authenticated/financial/'
      path: '/financial'
      fullPath: '/financial/'
      preLoaderRoute: typeof AuthenticatedFinancialIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/financial': {
      id: '/_authenticated/settings/financial'
      path: '/settings/financial'
      fullPath: '/settings/financial'
      preLoaderRoute: typeof AuthenticatedSettingsFinancialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/agenda': {
      id: '/_authenticated/settings/agenda'
      path: '/settings/agenda'
      fullPath: '/settings/agenda'
      preLoaderRoute: typeof AuthenticatedSettingsAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/revenues': {
      id: '/_authenticated/financial/revenues'
      path: '/financial/revenues'
      fullPath: '/financial/revenues'
      preLoaderRoute: typeof AuthenticatedFinancialRevenuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/reports': {
      id: '/_authenticated/financial/reports'
      path: '/financial/reports'
      fullPath: '/financial/reports'
      preLoaderRoute: typeof AuthenticatedFinancialReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/quotas': {
      id: '/_authenticated/financial/quotas'
      path: '/financial/quotas'
      fullPath: '/financial/quotas'
      preLoaderRoute: typeof AuthenticatedFinancialQuotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/payables': {
      id: '/_authenticated/financial/payables'
      path: '/financial/payables'
      fullPath: '/financial/payables'
      preLoaderRoute: typeof AuthenticatedFinancialPayablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/new': {
      id: '/_authenticated/financial/new'
      path: '/financial/new'
      fullPath: '/financial/new'
      preLoaderRoute: typeof AuthenticatedFinancialNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/fixed': {
      id: '/_authenticated/financial/fixed'
      path: '/financial/fixed'
      fullPath: '/financial/fixed'
      preLoaderRoute: typeof AuthenticatedFinancialFixedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/expenses': {
      id: '/_authenticated/financial/expenses'
      path: '/financial/expenses'
      fullPath: '/financial/expenses'
      preLoaderRoute: typeof AuthenticatedFinancialExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/$id': {
      id: '/_authenticated/financial/$id'
      path: '/financial/$id'
      fullPath: '/financial/$id'
      preLoaderRoute: typeof AuthenticatedFinancialIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda/proposals': {
      id: '/_authenticated/agenda/proposals'
      path: '/agenda/proposals'
      fullPath: '/agenda/proposals'
      preLoaderRoute: typeof AuthenticatedAgendaProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda/new': {
      id: '/_authenticated/agenda/new'
      path: '/agenda/new'
      fullPath: '/agenda/new'
      preLoaderRoute: typeof AuthenticatedAgendaNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda/$id': {
      id: '/_authenticated/agenda/$id'
      path: '/agenda/$id'
      fullPath: '/agenda/$id'
      preLoaderRoute: typeof AuthenticatedAgendaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgendaIdRoute: typeof AuthenticatedAgendaIdRoute
  AuthenticatedAgendaNewRoute: typeof AuthenticatedAgendaNewRoute
  AuthenticatedAgendaProposalsRoute: typeof AuthenticatedAgendaProposalsRoute
  AuthenticatedFinancialIdRoute: typeof AuthenticatedFinancialIdRoute
  AuthenticatedFinancialExpensesRoute: typeof AuthenticatedFinancialExpensesRoute
  AuthenticatedFinancialFixedRoute: typeof AuthenticatedFinancialFixedRoute
  AuthenticatedFinancialNewRoute: typeof AuthenticatedFinancialNewRoute
  AuthenticatedFinancialPayablesRoute: typeof AuthenticatedFinancialPayablesRoute
  AuthenticatedFinancialQuotasRoute: typeof AuthenticatedFinancialQuotasRoute
  AuthenticatedFinancialReportsRoute: typeof AuthenticatedFinancialReportsRoute
  AuthenticatedFinancialRevenuesRoute: typeof AuthenticatedFinancialRevenuesRoute
  AuthenticatedSettingsAgendaRoute: typeof AuthenticatedSettingsAgendaRoute
  AuthenticatedSettingsFinancialRoute: typeof AuthenticatedSettingsFinancialRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
  AuthenticatedFinancialIndexRoute: typeof AuthenticatedFinancialIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgendaIdRoute: AuthenticatedAgendaIdRoute,
  AuthenticatedAgendaNewRoute: AuthenticatedAgendaNewRoute,
  AuthenticatedAgendaProposalsRoute: AuthenticatedAgendaProposalsRoute,
  AuthenticatedFinancialIdRoute: AuthenticatedFinancialIdRoute,
  AuthenticatedFinancialExpensesRoute: AuthenticatedFinancialExpensesRoute,
  AuthenticatedFinancialFixedRoute: AuthenticatedFinancialFixedRoute,
  AuthenticatedFinancialNewRoute: AuthenticatedFinancialNewRoute,
  AuthenticatedFinancialPayablesRoute: AuthenticatedFinancialPayablesRoute,
  AuthenticatedFinancialQuotasRoute: AuthenticatedFinancialQuotasRoute,
  AuthenticatedFinancialReportsRoute: AuthenticatedFinancialReportsRoute,
  AuthenticatedFinancialRevenuesRoute: AuthenticatedFinancialRevenuesRoute,
  AuthenticatedSettingsAgendaRoute: AuthenticatedSettingsAgendaRoute,
  AuthenticatedSettingsFinancialRoute: AuthenticatedSettingsFinancialRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
  AuthenticatedFinancialIndexRoute: AuthenticatedFinancialIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
